theme: jekyll-theme-dinky
title: Technical Dave's Playpen
description: just a place to sandbox and start my templates 
I am putting in an image, see?
![Image of pretteh field](https://user-images.githubusercontent.com/79869773/109833233-185c7c00-7c0f-11eb-8bbe-d66d3cd419a4.jpg)
