theme: jekyll-theme-dinky
title: Technical Dave's Playpen
description: just a place to sandbox and start my templates 
#does this go here
![Image](https://github.com/TechnicalDave/technicaldave.github.io/issues/7#issue-821511514)
